### PR TITLE
Support for Oracle Linux added

### PR DESCRIPTION
**Pull request by wfsaxton**
Fixes https://github.com/kschu91/puppet-gogs/issues/10

### CODE REVIEW

**Comment by kschu91** [comment]
Thanks for that. I will merge that tomorrow.
Could you add a beaker test for OracleLinux in travis.yml? You have to add a new nodeset yml file for that in spec/acceptance/nodesets

**Comment by wfsaxton** [comment]
Just FYI, this is my first pull request ever.  I don't know what Beaker and Travis are, though I kind of figured it out by the way the pull request behaved where some automated tests happened automatically.

Although I can try to figure it out tomorrow.  Is there some kind of environment I should set up locally to do this?  Or should I risk it and just copy an existing test, modify/commit it, then submit the pull request and allow travis-ci to test it out?

**Comment by wfsaxton** [comment]
Yeah, I just took a look and all that is Greek to me...I wouldn't want to break anything.

Unless you have instructions on how I can set that all up in a local environment to test it out beforehand, I wouldn't feel comfortable adding those tests in.

**Comment by kschu91** [comment]
[1.1.0](https://travis-ci.org/kschu91/puppet-gogs/builds/208568524) is currently building on travis. As soon as the build is green the version will be automatically published to forge.
The new release contains your pull request.

**Pull request merged**
